version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-faq
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: techsolutions
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  web:
    build: ./web
    container_name: apache-faq
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    driver: bridge
