version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-faq
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: techsolutions
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  web1:
    build: ./web1
    container_name: apache-faq1
    volumes:
      - ./web1:/var/www/html
    depends_on:
      - db
    ports:
      - "8090:80"
    networks:
      - backend
  
  web2:
    build: ./web2
    container_name: apache-faq2
    volumes:
      - ./web2:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend
      
  nginx:
    build: ./nginx
    container_name: nginx-faq
    depends_on:
      - web1
      - web2
    ports: 
      - "443:80"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
